[package]
name = "_sealwatch"
version = "0.1.0"
edition = "2021"

[lib]
name = "spam_rs"  # This is the module name, matching what Python will import
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
numpy = "0.21"